language: php

php:
  - 7.0

before_script:
  - env
  - mkdir Build; cd Build
  - VERSION=$( if [ $TRAVIS_TAG ] ; then echo $TRAVIS_TAG ; else echo "dev-${TRAVIS_BRANCH}#${TRAVIS_COMMIT}" ; fi )
  - |
    cat <<EOF > composer.json
    {
      "name": "neos/neos-base-distribution",
      "config": {
          "vendor-dir": "Packages/Libraries",
          "bin-dir": "bin"
      },
      "require": {
          "neos/neos": "^3.0",
          "moc/varnish": "${VERSION}"
      },
      "require-dev": {
          "typo3/buildessentials": "~4.0",
          "mikey179/vfsstream": "~1.6",
          "phpunit/phpunit": "~5.4.0"
      },
      "scripts": {
          "post-update-cmd": "Neos\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-install-cmd": "Neos\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-package-update": "Neos\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall",
          "post-package-install": "Neos\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall"
      }
    }
  - cat composer.json
  - composer update

script: bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/MOC.Varnish/Tests/Unit
