MOC:
  Varnish:
    cacheHeaders:
      defaultSharedMaximumAge: ~
    varnishUrl: 'http://127.0.0.1'
    # List of ignored  cache tags to skip when flushing caches by tag, e.g. 'TYPO3.Neos:Document' which is used in 'TYPO3.Neos:Menu' elements
    ignoredCacheTags: []

TYPO3:
  Neos:
    modules:
      administration:
        submodules:
          purging:
            label: 'Varnish cache purging'
            controller: '\MOC\Varnish\Controller\VarnishCacheController'
            description: 'Clear Varnish cache.'
            icon: 'icon-gear'
            resource: 'MOC_Varnish_Backend_Module_Varnish_ClearCache'
            additionalResources:
              styleSheets:
                - 'resource://MOC.Varnish/Public/Styles/Module.css'
    typoScript:
      autoInclude:
        'MOC.Varnish': TRUE

  Flow:
    object:
      excludeClasses:
        'friendsofsymfony.httpcache': ['FOS\\HttpCache\\.*']
