MOC:
  Varnish:
    # Cache header sending configuration
    cacheHeaders:
      # Default and maximum TTL in seconds
      defaultSharedMaximumAge: ~
      # Disable sending headers (useful for staging environments)
      disabled: FALSE
    # URL varnish is running on for purge requests
    varnishUrl: 'http://127.0.0.1'
    # Port to use for reverse lookup in backend module
    reverseLookupPort: ~
    # List of ignored  cache tags to skip when flushing caches by tag, e.g. 'TYPO3.Neos:Document' which is used in 'TYPO3.Neos:Menu' elements
    ignoredCacheTags: []
    # Log configuration
    log:
      backend: TYPO3\Flow\Log\Backend\FileBackend
      backendOptions:
        logFileURL: '%FLOW_PATH_DATA%Logs/Varnish.log'
        createParentDirectories: TRUE
        severityThreshold: '%LOG_INFO%'
        maximumLogFileSize: 1048576
        logFilesToKeep: 1

TYPO3:
  Neos:
    modules:
      administration:
        submodules:
          varnish:
            label: 'Varnish cache purging'
            controller: '\MOC\Varnish\Controller\VarnishCacheController'
            description: 'Clear Varnish cache.'
            icon: 'icon-gear'
            resource: 'MOC_Varnish_Backend_Module_Varnish_ClearCache'
            additionalResources:
              styleSheets:
                - 'resource://MOC.Varnish/Public/Styles/Module.css'
    typoScript:
      autoInclude:
        'MOC.Varnish': TRUE

  Flow:
    object:
      excludeClasses:
        'friendsofsymfony.httpcache': ['FOS\\HttpCache\\.*']
        'guzzle.guzzle': ['Guzzle\\.*']
